// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC32xw_zev5qXblxBeqZ_bcSETeNVOtu5s',
    appId: '1:959908824104:android:3a29cd4b5fe77a6b22a11d',
    messagingSenderId: '959908824104',
    projectId: 'fir-authexample-a55f8',
    storageBucket: 'fir-authexample-a55f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxQ_G9JSVZqfqtix_c9YARlH3rtDjg5f0',
    appId: '1:959908824104:ios:4e0531a892678f8f22a11d',
    messagingSenderId: '959908824104',
    projectId: 'fir-authexample-a55f8',
    storageBucket: 'fir-authexample-a55f8.appspot.com',
    iosClientId: '959908824104-8ilsnj6ht3bkp5s9433ut0ul0f6g6mc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxQ_G9JSVZqfqtix_c9YARlH3rtDjg5f0',
    appId: '1:959908824104:ios:4e0531a892678f8f22a11d',
    messagingSenderId: '959908824104',
    projectId: 'fir-authexample-a55f8',
    storageBucket: 'fir-authexample-a55f8.appspot.com',
    iosClientId: '959908824104-8ilsnj6ht3bkp5s9433ut0ul0f6g6mc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthExample',
  );
}
